#!/usr/bin/env python3
"""
gen_coverage_bins.py
Parse reg_drv*.h files and generate coverage_bins.py.

Usage: python gen_coverage_bins.py <reg_drv_dir> [output_path]
  reg_drv_dir: directory containing reg_drv*.h files
  output_path: where to write coverage_bins.py (default: python/coverage_bins.py)
"""

import re, os, sys

def parse_struct_fields(text: str) -> list:
    """Parse bit-field declarations from a typedef struct block.
    Returns list of (field_name, bit_width). Skips __pad* fields.
    """
    fields = []
    for m in re.finditer(r'(\w+)\s+(\w+)\s*:\s*(\d+)\s*;', text):
        ftype, fname, fwidth = m.group(1), m.group(2), int(m.group(3))
        if fname.startswith('__pad'):
            continue
        fields.append((fname, fwidth))
    return fields

def parse_reg_drv(content: str) -> dict:
    """Parse reg_drv.h content and return struct database.
    
    Returns dict of:
        arrays: {name_mem: {'depth': N, 'fields': [(name, width), ...]}}  (memory arrays)
        singletons: {name: {'fields': [(name, width), ...]}}                (single registers)
    """
    arrays = {}
    singletons = {}
    
    # Find all typedef struct blocks and their following declarations
    # Pattern: /* ... */ typedef struct { ... } TypeName;
    # First, find all typedef struct blocks
    struct_pattern = re.compile(
        r'typedef\s+struct\s*\{([^}]+)\}\s*(\w+)_entry_t\s*;',
        re.DOTALL
    )
    singleton_pattern = re.compile(
        r'typedef\s+struct\s*\{([^}]+)\}\s*(\w+)_t\s*;',
        re.DOTALL
    )
    
    processed_arrays = set()
    
    for m in struct_pattern.finditer(content):
        fields_text = m.group(1)
        type_name = m.group(2)
        
        fields = parse_struct_fields(fields_text)
        if not fields:
            continue
        
        # Find array declaration after this typedef: TypeName_entry_t TypeName_mem[DEPTH];
        # Search in the rest of the content after this match
        rest = content[m.end():]
        arr_m = re.search(rf'{type_name}_entry_t\s+(\w+)\[(\d+)\];', rest)
        if arr_m:
            mem_name = arr_m.group(1)
            depth = int(arr_m.group(2))
            arrays[mem_name] = {'depth': depth, 'fields': fields}
            processed_arrays.add(type_name)
    
    # Process singletons
    for m in singleton_pattern.finditer(content):
        fields_text = m.group(1)
        type_name = m.group(2)
        
        fields = parse_struct_fields(fields_text)
        if not fields:
            continue
        
        # Check if this type was already used as an array
        if type_name in processed_arrays:
            continue
        
        # Find extern declaration after this typedef
        rest = content[m.end():]
        ext_m = re.search(rf'extern\s+{type_name}_t\s+(\w+)\s*;', rest)
        if ext_m:
            inst_name = ext_m.group(1)
            singletons[inst_name] = {'fields': fields}
    
    return arrays, singletons

def generate_coverage_bins(arrays: dict, singletons: dict) -> str:
    """Generate coverage_bins.py content."""
    
    def bin_for_field(struct_name: str, field_name: str, width: int) -> str:
        key = f"{struct_name}.{field_name}"
        if width == 1:
            return f'        **_b1("{key}"),'
        elif width == 2:
            return f'        **_b2("{key}"),'
        elif width == 3:
            return f'        **_b3("{key}"),'
        elif width == 4:
            return f'        **_b4("{key}"),'
        elif width <= 8:
            return f'        **_bm("{key}",{width}),'
        else:
            return f'        **_bw("{key}"),'
    
    lines = []
    lines.append("# Auto-generated from reg_drv*.h — do not edit")
    lines.append("# Generated by gen_coverage_bins.py")
    lines.append("")
    lines.append("def _b1(n): return {f'{n}=0':0, f'{n}=1':0}")
    lines.append("def _b2(n): return {f'{n}={v}':0 for v in range(4)}")
    lines.append("def _b3(n): return {f'{n}={v}':0 for v in range(8)}")
    lines.append("def _b4(n): return {f'{n}={v}':0 for v in range(16)}")
    lines.append("def _bw(n): return {f'{n}=0':0, f'{n}=nonzero':0, f'{n}=max':0}")
    lines.append("def _bm(n,w): return {f'{n}=0':0, f'{n}=mid':0, f'{n}={2**w-1}':0}")
    lines.append("")
    lines.append("def get_register_bins():")
    lines.append('    """Return dict of {coverpoint_name: {bin_name: 0}} for all register fields."""')
    lines.append("    bins = {}")
    lines.append("    def A(n, d): bins[n] = d")
    lines.append("")
    
    for mem_name, info in sorted(arrays.items()):
        lines.append(f"    # -- {mem_name}[{info['depth']}] --")
        lines.append(f"    A('{mem_name}', {{")
        for fname, fwidth in info['fields']:
            lines.append(bin_for_field(mem_name, fname, fwidth))
        lines.append("    })")
        lines.append("")
    
    for inst_name, info in sorted(singletons.items()):
        lines.append(f"    # -- {inst_name} (singleton) --")
        lines.append(f"    A('{inst_name}', {{")
        for fname, fwidth in info['fields']:
            lines.append(bin_for_field(inst_name, fname, fwidth))
        lines.append("    })")
        lines.append("")
    
    lines.append("    return bins")
    lines.append("")
    return "\n".join(lines)

def main():
    if len(sys.argv) < 2:
        print("Usage: python gen_coverage_bins.py <reg_drv_dir> [output_path]")
        sys.exit(1)
    
    src_dir = sys.argv[1]
    out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), 'python', 'coverage_bins.py')
    
    # Read all reg_drv*.h files
    all_content = ""
    for fname in sorted(os.listdir(src_dir)):
        if fname.startswith('reg_drv') and fname.endswith('.h'):
            fpath = os.path.join(src_dir, fname)
            with open(fpath, 'r', encoding='utf-8') as f:
                all_content += f.read() + "\n"
    
    if not all_content:
        print(f"ERROR: No reg_drv*.h files found in {src_dir}")
        sys.exit(1)
    
    arrays, singletons = parse_reg_drv(all_content)
    
    total_fields = sum(len(info['fields']) for info in arrays.values())
    total_fields += sum(len(info['fields']) for info in singletons.values())
    
    print(f"Parsed {len(arrays)} array structs + {len(singletons)} singletons = {total_fields} fields")
    for name in sorted(arrays): print(f"  {name}[{arrays[name]['depth']}]: {len(arrays[name]['fields'])} fields")
    for name in sorted(singletons): print(f"  {name}: {len(singletons[name]['fields'])} fields")
    
    content = generate_coverage_bins(arrays, singletons)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"\nWritten {len(content)} bytes to {out_path}")

if __name__ == '__main__':
    main()
