"""
compiler/codegen/switch_api_gen.py
Automatically generate switch_api_gen.c / switch_api_gen.h from reg_map + trace info.

Produces getter/setter functions for every register field, plus trace index getters.
The generated files are #included by the hand-written tb_runtime.c.
"""

from __future__ import annotations
from typing import List


def _c_type_and_mask(field) -> tuple:
    """Return (C integer type, bitmask) for a field."""
    w = field.width or 1
    if w <= 8:
        return "int", (1 << w) - 1
    elif w <= 16:
        return "int", (1 << w) - 1
    else:
        return "int", 0xFFFFFFFF


def _ok_macro(name: str, depth: int) -> str:
    """Return the bounds-check macro name + definition for a struct."""
    macro = f"{name.upper()}_OK"
    defn = f"#define {macro}(i) ((i)>=0 && (i)<{depth})"
    return macro, defn


def _generate_header(reg_map, trace_idx_names: List[str]) -> str:
    """Generate switch_api_gen.h — all getter/setter declarations."""
    lines = []
    lines.append("/* Auto-generated by 8m compiler — do not edit */")
    lines.append("#ifndef _SWITCH_API_GEN_H_")
    lines.append("#define _SWITCH_API_GEN_H_")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")

    # ── MemTables (array structs) ──
    for mt in reg_map.mem_tables:
        name = mt.name
        lines.append(f"/* -- {name}_mem[{mt.num_entries}] -- */")
        for fld in mt.fields:
            if fld.name.startswith("__pad"):
                continue
            lines.append(f"int switch_{name}_{fld.name}(int idx);")
            lines.append(f"void switch_set_{name}_{fld.name}(int idx, int v);")
        lines.append("")

    # ── Registers (singletons) ──
    for reg in reg_map.registers:
        name = reg.name
        # Skip register arrays handled as mem_tables
        if reg.words > 1 and any(f.name.startswith("vlanId") for f in reg.fields):
            # Special: VlanIdCamCtl has 16 individual fields
            lines.append(f"/* -- {name} (singleton) -- */")
            for fld in reg.fields:
                if fld.name.startswith("__pad"):
                    continue
                lines.append(f"int switch_{name}_{fld.name}(int i);")
                lines.append(f"void switch_set_{name}_{fld.name}(int i, int v);")
        else:
            lines.append(f"/* -- {name} (singleton) -- */")
            for fld in reg.fields:
                if fld.name.startswith("__pad"):
                    continue
                lines.append(f"int switch_{name}_{fld.name}(void);")
                lines.append(f"void switch_set_{name}_{fld.name}(int v);")
        lines.append("")

    # ── Trace index getters ──
    lines.append("/* -- Trace index getters -- */")
    for tname in trace_idx_names:
        lines.append(f"int switch_{tname}(void);")
    lines.append("")

    # ── Parser reset ──
    lines.append("/* -- Parser globals reset -- */")
    lines.append("void switch_reset_parser_globals(void);")
    lines.append("")

    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")
    lines.append("")
    lines.append("#endif /* _SWITCH_API_GEN_H_ */")
    return "\n".join(lines)


def _generate_source(reg_map, trace_idx_names: List[str],
                     trace_vars: List[str],
                     extern_vars: List[str]) -> str:
    """Generate switch_api_gen.c — getter/setter implementations."""
    lines = []
    lines.append("/* Auto-generated by 8m compiler — do not edit */")
    lines.append('')
    lines.append('#include "switch_api_gen.h"')
    lines.append('#include "reg_drv_common.h"')

    # Include all reg_drv headers
    if hasattr(reg_map, 'mem_tables'):
        seen_headers = set()
        for mt in reg_map.mem_tables:
            hdr = f"reg_drv_{mt.name}.h" if hasattr(mt, 'source_file') else "reg_drv_tinyReg.h"
            seen_headers.add("reg_drv_tinyReg.h")
        for reg in reg_map.registers:
            seen_headers.add("reg_drv_tinyReg.h")
        # Also include tinyReg2 if prior maps exist
        seen_headers.add("reg_drv_tinyReg2.h")
        for h in sorted(seen_headers):
            lines.append(f'#include "{h}"')
    lines.append('#include "8m_trace_extern.h"')
    lines.append('#include <string.h>')
    lines.append('')

    # ── Trace index getters ──
    lines.append("/* ================================================================")
    lines.append(" * Trace index getters")
    lines.append(" * ================================================================ */")
    for tname in trace_idx_names:
        lines.append(f"int switch_{tname}(void) {{ return (int)g_trace_{tname}; }}")
    lines.append("")

    # ── Parser reset ──
    lines.append("/* ================================================================")
    lines.append(" * Parser globals reset")
    lines.append(" * ================================================================ */")
    parser_vars = [v for v in extern_vars if v.startswith('pr') or v == 'giTpid' or v == 'prIpDscp']
    lines.append("void switch_reset_parser_globals(void) {")
    for v in parser_vars:
        lines.append(f"    {v} = 0;")
    lines.append("}")
    lines.append("")

    # ── Helper macros ──
    lines.append("/* ================================================================")
    lines.append(" * Bounds-check macros")
    lines.append(" * ================================================================ */")
    for mt in reg_map.mem_tables:
        macro, defn = _ok_macro(mt.name, mt.num_entries)
        lines.append(defn)
    # Prior maps from tinyReg2
    lines.append("#define DS1QPRIORMAP_OK(i) ((i)>=0 && (i)<8)")
    lines.append("#define DSDSCPPRIORMAP_OK(i) ((i)>=0 && (i)<64)")
    lines.append("")

    # ── MemTable getters + setters ──
    for mt in reg_map.mem_tables:
        name = mt.name
        macro, _ = _ok_macro(name, mt.num_entries)
        array_name = f"{name}_mem"
        lines.append(f"/* -- {array_name}[{mt.num_entries}] -- */")
        for fld in mt.fields:
            if fld.name.startswith("__pad"):
                continue
            ctype, mask = _c_type_and_mask(fld)
            mask_str = f"0x{mask:X}" if mask < 0x10 else (f"0x{mask:03X}" if mask < 0x1000 else str(mask))
            # getter
            lines.append(
                f"int switch_{name}_{fld.name}(int idx) {{ "
                f"return {macro}(idx) ? ({ctype}){array_name}[idx].{fld.name} : 0; }}")
            # setter
            lines.append(
                f"void switch_set_{name}_{fld.name}(int idx, int v) {{ "
                f"if ({macro}(idx)) {array_name}[idx].{fld.name} = v & {mask_str}; }}")
        lines.append("")

    # ── Register getters + setters ──
    for reg in reg_map.registers:
        name = reg.name
        lines.append(f"/* -- {name} (singleton) -- */")
        for fld in reg.fields:
            if fld.name.startswith("__pad"):
                continue
            ctype, mask = _c_type_and_mask(fld)
            mask_str = f"0x{mask:X}" if mask < 0x10 else (f"0x{mask:03X}" if mask < 0x1000 else str(mask))
            lines.append(
                f"int switch_{name}_{fld.name}(void) {{ return ({ctype}){name}.{fld.name}; }}")
            lines.append(
                f"void switch_set_{name}_{fld.name}(int v) {{ {name}.{fld.name} = v & {mask_str}; }}")
        lines.append("")

    # ── Special: Ds1qPriorMap / DsDscpPriorMap (from tinyReg2) ──
    lines.append("/* -- Ds1qPriorMap_mem[8] -- */")
    lines.append("int switch_Ds1qPriorMap_prior(int idx) { return DS1QPRIORMAP_OK(idx) ? (int)Ds1qPriorMap_mem[idx].prior : 0; }")
    lines.append("void switch_set_Ds1qPriorMap_prior(int idx, int v) { if (DS1QPRIORMAP_OK(idx)) Ds1qPriorMap_mem[idx].prior = v & 3; }")
    lines.append("")
    lines.append("/* -- DsDscpPriorMap_mem[64] -- */")
    lines.append("int switch_DsDscpPriorMap_prior(int idx) { return DSDSCPPRIORMAP_OK(idx) ? (int)DsDscpPriorMap_mem[idx].prior : 0; }")
    lines.append("void switch_set_DsDscpPriorMap_prior(int idx, int v) { if (DSDSCPPRIORMAP_OK(idx)) DsDscpPriorMap_mem[idx].prior = v & 3; }")
    lines.append("")

    return "\n".join(lines)


def generate(reg_map, trace_idx_names: List[str] = None,
             trace_vars: List[str] = None,
             extern_vars: List[str] = None) -> tuple:
    """Generate switch_api_gen.h and switch_api_gen.c content.

    Args:
        reg_map: RegMapDef from the register parser
        trace_idx_names: list of trace index variable names (e.g. ['giHashIdx', ...])
        trace_vars: all trace variable names
        extern_vars: all extern global variable names from 8m_globals_extern.h

    Returns:
        (header_content, source_content) tuple of strings
    """
    if trace_idx_names is None:
        trace_idx_names = []
    if trace_vars is None:
        trace_vars = []
    if extern_vars is None:
        extern_vars = []

    header = _generate_header(reg_map, trace_idx_names)
    source = _generate_source(reg_map, trace_idx_names, trace_vars, extern_vars)
    return header, source


# ================================================================
# Coverage bin auto-generation
# ================================================================

def _coverage_bin_for_field(struct_name: str, field_name: str, width: int) -> str:
    """Generate the coverage bin dict entry for a single field."""
    key = f"{struct_name}.{field_name}"
    if width == 1:
        return f'        **_b1("{key}"),'
    elif width == 2:
        return f'        **_b2("{key}"),'
    elif width == 3:
        return f'        **_b3("{key}"),'
    elif width == 4:
        return f'        **_b4("{key}"),'
    elif width <= 8:
        return f'        **_bm("{key}",{width}),'
    else:
        return f'        **_bw("{key}"),'


def generate_coverage_bins(reg_map) -> str:
    """Generate coverage_bins.py content with all register field bins.

    Returns a Python module string that coverage.py can import.
    """
    lines = []
    lines.append("# Auto-generated by 8m compiler — do not edit")
    lines.append("# Import this from coverage.py to get all register field bins.")
    lines.append("")
    lines.append("def _b1(n): return {f'{n}=0':0, f'{n}=1':0}")
    lines.append("def _b2(n): return {f'{n}={v}':0 for v in range(4)}")
    lines.append("def _b3(n): return {f'{n}={v}':0 for v in range(8)}")
    lines.append("def _b4(n): return {f'{n}={v}':0 for v in range(16)}")
    lines.append("def _bw(n): return {f'{n}=0':0, f'{n}=nonzero':0, f'{n}=max':0}")
    lines.append("def _bm(n,w): return {f'{n}=0':0, f'{n}=mid':0, f'{n}={2**w-1}':0}")
    lines.append("")
    lines.append("def get_register_bins():")
    lines.append('    """Return dict of {coverpoint_name: {bin_name: 0}} for all register fields."""')
    lines.append("    bins = {}")
    lines.append("")
    lines.append("    def A(n, d): bins[n] = d")
    lines.append("")

    for mt in reg_map.mem_tables:
        name = mt.name
        array_name = f"{name}_mem"
        lines.append(f"    # -- {array_name}[{mt.num_entries}] --")
        lines.append(f"    A('{array_name}', {{")
        for fld in mt.fields:
            if fld.name.startswith("__pad"):
                continue
            lines.append(_coverage_bin_for_field(array_name, fld.name, fld.width or 1))
        lines.append("    })")
        lines.append("")

    for reg in reg_map.registers:
        name = reg.name
        lines.append(f"    # -- {name} (singleton) --")
        lines.append(f"    A('{name}', {{")
        for fld in reg.fields:
            if fld.name.startswith("__pad"):
                continue
            lines.append(_coverage_bin_for_field(name, fld.name, fld.width or 1))
        lines.append("    })")
        lines.append("")

    # Prior maps from tinyReg2
    lines.append("    # -- Ds1qPriorMap_mem[8] --")
    lines.append("    A('Ds1qPriorMap_mem', {**_b2('Ds1qPriorMap_mem.prior')})")
    lines.append("")
    lines.append("    # -- DsDscpPriorMap_mem[64] --")
    lines.append("    A('DsDscpPriorMap_mem', {**_b2('DsDscpPriorMap_mem.prior')})")
    lines.append("")
    lines.append("    return bins")
    lines.append("")

    return "\n".join(lines)
